### ISSUE TITLE
How to get the return value of "ComputeInformationGain"

### ISSUE THREAD

**Issue by LaLaLailalai** [johannesu/sherwood-classify-matlab#1]
Hi~
     I want to use this good project to classify 2D data , but the accuracy is too low .So I want to know the exact weak learner which has the max value of information gain.  I found that the value is computed in the  file of ClassificationContext.h,but the function is private,and I can't find in which place this function had been called.Can you tell me how to get this value  in your project?Dose the file "forest.bin" save related information?
    I would appreciate your help very much !

**Comment by johannesu** [comment]
The serialization code generating the default name `forest.bin` is located in  `/include/Serialize.h`
`.

Depending on your splitting criteria you may either serialize `RandomHyperplaneFeatureResponse` or `AxisAlignedFeatureResponse` classes containing the parameters you would need.

If you need these values you have to either
1) Modify the mex code such that they are printed or returned to matlab.
or
2) Write a small program using `Seralize.h` which deseralizes forest.bin and then gives you the same information.
